In [9]:
import pandas as pd
import librosa
import io
import numpy as np


In [10]:
data_path = "0000.parquet"
df = pd.read_parquet(data_path)
display(df)

audio  song_id  genre_id  \
0    {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...       66        13   
1    {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...      150        13   
2    {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...      202        13   
3    {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...      402        13   
4    {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...      512        13   
..                                                 ...      ...       ...   
301  {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...    24619        13   
302  {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...    24780        13   
303  {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...    24915        13   
304  {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...    24967        13   
305  {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x...    24983        13   

    genre  
0    Jazz  
1    Jazz  
2    Jazz  
3    Jazz  
4    Jazz  
..    ...  
301  Jazz  
302  Jazz  
303  Jazz  
304  Jazz  
305  Jazz  

[306 rows x 4 columns]

In [12]:

# Function to convert audio bytes to waveform
def bytes_to_waveform(audio_bytes):
    # Decode the byte array to an audio format
    audio_buffer = io.BytesIO(audio_bytes)
    # Load the audio file using librosa
    waveform, sr = librosa.load(audio_buffer, sr=None)
    return waveform, sr

# Load your DataFrame
# df = pd.read_parquet('your_parquet_file.parquet')

# Extract waveforms and sample rates
waveforms = []
for index, row in df.iterrows():
    audio_bytes = row['audio']['bytes']
    waveform, sr = bytes_to_waveform(audio_bytes)
    waveforms.append(waveform)

# Convert list of waveforms to numpy array for further processing
waveforms = np.array(waveforms, dtype=object)

print(f"Loaded {len(waveforms)} audio samples.")

Loaded 306 audio samples.


In [13]:
display(waveforms)

array([array([-2.5669800e-10,  5.3917176e-10,  3.8325849e-09, ...,
              -1.7219001e-02, -2.4834994e-02, -3.0671513e-02], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ..., -0.12589079,
              -0.21114007, -0.2635392 ], dtype=float32)               ,
       array([0.        , 0.        , 0.        , ..., 0.40975037, 0.38618648,
              0.35830998], dtype=float32)                                     ,
       array([ 1.7316817e-10,  1.4437651e-09, -4.0869197e-10, ...,
              -6.6732094e-02, -6.3906908e-02, -6.1076727e-02], dtype=float32),
       array([-3.9696783e-08, -1.5343664e-07, -5.6330020e-07, ...,
              -8.1041530e-02, -7.6655284e-02, -7.1424194e-02], dtype=float32),
       array([ 7.41303408e-10,  7.26783211e-09,  1.74853128e-08, ...,
              -1.09082066e-01, -1.17137432e-01, -1.22750327e-01], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ..., -0.05701961,
              -0.05512334, -0.0522383